[package]
name = "turya-core"
version = "0.1.0"
edition = "2021"

[dependencies]
turya-protocol = { path = "../turya-protocol" }
turya-tools = { path = "../turya-tools" }
tokio = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
